import { ArrowRight, BadgeCheck, Leaf, MapPin, Star, Store, Users } from "lucide-react"
import { Link } from "react-router-dom"
import Navbar from "../../../components/public/navbar"
import Footer from "../../../components/public/Footer"

const businesses = [
  { name: "Samarqand nonvoyxonasi", type: "Nonvoyxona", location: "Chilonzor, Toshkent", rating: "4.9", offers: "12 ta faol taklif", image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1100&q=85" },
  { name: "Green Bowl", type: "Sog‘lom ovqatlar", location: "Yunusobod, Toshkent", rating: "4.8", offers: "8 ta faol taklif", image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1100&q=85" },
  { name: "Coffee Corner", type: "Kafe", location: "Mirzo Ulug‘bek, Toshkent", rating: "4.7", offers: "6 ta faol taklif", image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1100&q=85" },
  { name: "Fresh Market", type: "Meva va sabzavotlar", location: "Yashnobod, Toshkent", rating: "4.9", offers: "10 ta faol taklif", image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=1100&q=85" },
  { name: "Mehr Bakery", type: "Qandolat", location: "Shayxontohur, Toshkent", rating: "5.0", offers: "5 ta faol taklif", image: "https://images.unsplash.com/photo-1551024506-0BCCd828d307?auto=format&fit=crop&w=1100&q=85" },
  { name: "Mazali Dasturxon", type: "Restoran", location: "Olmazor, Toshkent", rating: "4.8", offers: "9 ta faol taklif", image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1100&q=85" },
]

const Businesses = () => (
  <div className="min-h-screen bg-[#f7f5f0] text-slate-900">
    <Navbar />
    <main className="mx-auto max-w-[1280px] px-5 pb-20 pt-12 sm:px-8 lg:px-10 lg:pt-20">
      <section className="grid items-center gap-10 lg:grid-cols-[1fr_0.8fr]"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-800"><Leaf className="size-4" /> Qolmasin hamkorlari</div><h1 className="max-w-3xl text-5xl font-black leading-[0.95] tracking-[-0.065em] sm:text-7xl">Yaxshi bizneslarni <span className="text-emerald-800">yaqindan</span> taning.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Sizga yaqin restoran, kafe, nonvoyxona va do‘konlarni toping. Ularning foydali takliflarini ko‘rib, mahalliy bizneslarni qo‘llab-quvvatlang.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/offers" className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-6 py-4 font-bold text-white transition hover:bg-orange-400">Takliflarni ko‘rish <ArrowRight className="size-4" /></Link><span className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white/70 px-5 py-4 font-semibold text-slate-600"><BadgeCheck className="size-5 text-emerald-700" /> Tekshirilgan bizneslar</span></div></div><div className="relative min-h-[350px] overflow-hidden rounded-[2rem] bg-[#dcebe3] shadow-[0_20px_45px_rgba(15,23,42,0.1)]"><img src="https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1300&q=85" alt="Qolmasin hamkor restorani" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#092f27]/65 to-transparent" /><div className="absolute bottom-0 left-0 p-6 text-white"><p className="text-3xl font-black">120+</p><p className="mt-1 text-sm text-white/80">hamkor bizneslar</p></div></div></section>
      <section className="mt-20" aria-labelledby="businesses-heading"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-bold uppercase tracking-[0.18em] text-orange-600">Sizga yaqin</p><h2 id="businesses-heading" className="text-4xl font-black tracking-[-0.05em] sm:text-5xl">Hamkor bizneslar</h2></div><div className="flex items-center gap-2 text-sm text-slate-500"><MapPin className="size-4 text-emerald-700" /> Toshkent bo‘yicha</div></div><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{businesses.map((business) => <article key={business.name} className="group overflow-hidden rounded-[1.7rem] border border-slate-200 bg-white shadow-[0_12px_30px_rgba(15,23,42,0.06)] transition hover:-translate-y-1 hover:shadow-[0_18px_35px_rgba(15,23,42,0.11)]"><div className="h-52 overflow-hidden"><img src={business.image} alt={business.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-5"><div className="flex items-center justify-between gap-3 text-sm"><span className="font-medium text-emerald-700">{business.type}</span><span className="inline-flex items-center gap-1 font-bold text-orange-500"><Star className="size-4 fill-current" />{business.rating}</span></div><h3 className="mt-3 text-xl font-bold">{business.name}</h3><p className="mt-2 inline-flex items-center gap-1.5 text-sm text-slate-500"><MapPin className="size-4" />{business.location}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-sm text-slate-500">{business.offers}</span><Link to="/offers" aria-label={`${business.name} takliflarini ko‘rish`} className="grid size-9 place-items-center rounded-full bg-emerald-50 text-emerald-800 transition hover:bg-emerald-800 hover:text-white"><ArrowRight className="size-4" /></Link></div></div></article>)}</div></section>
      <section className="mt-20 grid gap-5 md:grid-cols-2"><div className="rounded-[2rem] bg-[#0c6f56] p-8 text-white sm:p-10"><span className="grid size-12 place-items-center rounded-2xl bg-white/10"><Store className="size-6" /></span><h2 className="mt-7 text-3xl font-black tracking-[-0.05em]">Biznesingizni qo‘shing</h2><p className="mt-4 max-w-lg leading-7 text-emerald-50/75">Yaxshi mahsulotlaringizni yangi xaridorlarga yetkazing, daromadni oshiring va isrofni kamaytiring.</p><Link to="/register" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-orange-400 px-5 py-3.5 font-bold text-slate-900 transition hover:bg-orange-300">Hamkor bo‘lish <ArrowRight className="size-4" /></Link></div><div className="rounded-[2rem] bg-[#f0e9dc] p-8 sm:p-10"><span className="grid size-12 place-items-center rounded-2xl bg-white/70 text-orange-600"><Users className="size-6" /></span><h2 className="mt-7 text-3xl font-black tracking-[-0.05em]">Mahalliy joylarni kashf eting</h2><p className="mt-4 max-w-lg leading-7 text-slate-600">Yaqin atrofdagi yangi ta’mlarni sinab ko‘ring va har bir xarid bilan yaxshi tashabbusni qo‘llab-quvvatlang.</p><Link to="/offers" className="mt-7 inline-flex items-center gap-2 font-bold text-emerald-800 transition hover:text-orange-600">Takliflarni topish <ArrowRight className="size-4" /></Link></div></section>
    </main>
    <Footer />
  </div>
)

export default Businesses
